/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as RoomRoomIdCameraRouteImport } from './routes/room.$roomId.camera'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdCameraRoute = RoomRoomIdCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => RoomRoomIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/room/$roomId': typeof RoomRoomIdRouteWithChildren
  '/room/$roomId/camera': typeof RoomRoomIdCameraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/room/$roomId': typeof RoomRoomIdRouteWithChildren
  '/room/$roomId/camera': typeof RoomRoomIdCameraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/room/$roomId': typeof RoomRoomIdRouteWithChildren
  '/room/$roomId/camera': typeof RoomRoomIdCameraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/room/$roomId' | '/room/$roomId/camera'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/room/$roomId' | '/room/$roomId/camera'
  id: '__root__' | '/' | '/room/$roomId' | '/room/$roomId/camera'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomRoomIdRoute: typeof RoomRoomIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/camera': {
      id: '/room/$roomId/camera'
      path: '/camera'
      fullPath: '/room/$roomId/camera'
      preLoaderRoute: typeof RoomRoomIdCameraRouteImport
      parentRoute: typeof RoomRoomIdRoute
    }
  }
}

interface RoomRoomIdRouteChildren {
  RoomRoomIdCameraRoute: typeof RoomRoomIdCameraRoute
}

const RoomRoomIdRouteChildren: RoomRoomIdRouteChildren = {
  RoomRoomIdCameraRoute: RoomRoomIdCameraRoute,
}

const RoomRoomIdRouteWithChildren = RoomRoomIdRoute._addFileChildren(
  RoomRoomIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomRoomIdRoute: RoomRoomIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
